services:
  app:
    build: .
    container_name: xrpl_remittance_system_backend
    command: npm run dev
    restart: always
    ports:
      - '3000:3000'
    env_file:
      - .env
    depends_on:
      - redis
    volumes:
      - .:/app
      - /app/node_modules

  email_worker:
    build: .
    container_name: xrpl_email_worker
    command: npm run emailWorker
    restart: always
    env_file:
      - .env
    depends_on:
      - redis
    volumes:
      - .:/app
      - /app/node_modules

  xrpl_payment_worker:
    build: .
    container_name: xrpl_payment_worker
    command: npm run xrplPaymentWorker
    restart: always
    env_file:
      - .env
    depends_on:
      - redis
    volumes:
      - .:/app
      - /app/node_modules

  redis:
    image: redis:7-alpine
    container_name: xrpl_redis
    restart: always
    ports:
      - '6380:6379'
